name = "latanime-stremio"
main = "src/index.ts"
compatibility_date = "2025-09-15"
compatibility_flags = ["nodejs_compat"]

[browser]
binding = "MYBROWSER"

[vars]
TMDB_API_KEY = ""
PLAYWRIGHT_URL = "https://latanime-bridge.onrender.com"
BRIDGE_API_KEY = ""
