name = "latanime-stremio"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[vars]
TMDB_API_KEY = ""
PLAYWRIGHT_URL = "https://latanime-bridge.onrender.com"
BRIDGE_API_KEY = ""
