name = "latanime-stremio"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat_v2"]

[browser]
binding = "MYBROWSER"

[vars]
TMDB_API_KEY = ""
PLAYWRIGHT_URL = "https://latanime-bridge.onrender.com"
BRIDGE_API_KEY = ""
